# Generated by Django 6.0.2 on 2026-03-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('bread', 'Breads'), ('pastry', 'Pastries'), ('cupcake', 'Cupckaes'), ('cake', 'Cakes'), ('cookie', 'Cookies'), ('sweet', 'Sweets'), ('snack', 'Snacks & Namkeen'), ('hot_beverage', 'Hot Beverages'), ('cold_beverage', 'Cold Beverages'), ('ice_cream', 'Ice Creams')], max_length=30)),
                ('food_type', models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('egg', 'Contains Only Egg')], max_length=15)),
                ('is_available', models.BooleanField(default=True)),
                ('average_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
            ],
        ),
    ]
