# Generated by Django 6.0.2 on 2026-04-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_products_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bread-and-bun', 'Breads & Buns'), ('cake-and-pastry', 'Cakes & Pastries'), ('cupcake', 'Cupcakes'), ('biscuit-and-cookie', 'Biscuits & Cookies'), ('sweet', 'Sweets'), ('snack', 'Snacks & Namkeen'), ('hot-beverage', 'Hot Beverages'), ('cold-beverage', 'Cold Beverages'), ('ice-cream', 'Ice Creams')], max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='food_type',
            field=models.CharField(choices=[('veg', 'Pure Veg'), ('non-veg', 'Non-Veg'), ('egg', 'Contains Egg')], max_length=15),
        ),
    ]
