# Generated by Django 6.0.2 on 2026-04-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category_alter_product_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('breads-and-buns', 'Breads & Buns'), ('cakes-and-pastries', 'Cakes & Pastries'), ('cupcakes', 'Cupcakes'), ('biscuits-and-cookies', 'Biscuits & Cookies'), ('sweets', 'Sweets'), ('snacks', 'Snacks & Namkeen'), ('hot-beverages', 'Hot Beverages'), ('cold-beverages', 'Cold Beverages'), ('ice-creams', 'Ice Creams')], max_length=30),
        ),
    ]
